config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  root "flights#index"

  get "booking" => "bookings#manage", as: :manage_booking

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup" => "users#new"

  get "airports" => "airports#index"

  get "search_flight" => "flights#search_flights"

  post "users/check_email" => "users#check_email", as: :check_email
  post "users/check_username" => "users#check_username", as: :check_username
  post "sessions/check_username_email" => "sessions#check_username_email",
    as: :check_username_email

  resources :users, path: "/profile"
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :departure_location, class_name: "Airport"
  belongs_to :arrival_location, class_name: "Airport"
  has_many :bookings
  has_many :passengers

  scope :location, (
    lambda do |loc|
      where("departure_location_id = ?", loc)
    end
  )

  scope :destination, (
    lambda do |dest|
      where("arrival_location_id = ?", dest)
    end
  )

  scope :when, (
    lambda do |ddate|
      where("departure_date > ?", (Date.parse(ddate) - 1).to_time).
        where("departure_date < ?", (Date.parse(ddate) + 1).to_time)
    end
  )

  validates :departure_location_id,
            :arrival_location_id,
            :flight_number,
            :airline,
            :departure_date,
            :arrival_date,
            presence: true

  def self.filter(filtering_params)
    results = where(nil)
    filtering_params.each do |key, value|
      results = results.public_send(key, value) if value.present?
    end
    results
  end
end

app/controllers/flight_controller.rb
class FlightController < ApplicationController
  def index
  end

  def search_flights
    available_flights = Flight.filter(
      when: params[:when],
      location: params[:location],
      destination: params[:destination]
    )

    flights = []
    available_flights.each do |flight|
      flights << {
        id: flight.id,
        dtime: FlightPresenter.new(flight).departure_time,
        atime: FlightPresenter.new(flight).arrival_time,
        ddate: FlightPresenter.new(flight).ddate,
        adate: FlightPresenter.new(flight).adate,
        fnumber: flight.flight_number,
        airline: flight.airline,
        price: FlightPresenter.new(flight).flight_price,
        dport: {
          id: flight.departure_location.id,
          name: flight.departure_location.name,
          location: flight.departure_location.location
        },
        aport: {
          id: flight.arrival_location.id,
          name: flight.arrival_location.name,
          location: flight.arrival_location.location
        }
      }
    end

    @result = {
      count: flights.size,
      results: flights
    }

    respond_to do |format|
      format.html { render partial: "flight/search_result" }
      format.json { render json: @result.as_json }
    end
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
  end

  def search_flights
    @result = process_flights
    respond_to do |format|
      format.html { render partial: "flights/search_result" }
      format.json { render json: json_resp(@result) }
    end
  end

  private

  def get_flights
    Flight.filter(
      when: params[:when],
      location: params[:location],
      destination: params[:destination]
    )
  end

  def process_flights
    flights = get_flights.map(&FlightPresenter.method(:new))

    {
      count: flights.size,
      results: flights,
      passengers: params[:passengers]
    }
  end

  def json_resp(results)
    results.as_json(
      include: {
        departure_location: { only: [:name, :location] },
        arrival_location: { only: [:name, :location] }
      }
    )
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
  def logo(url = Faker::Company.logo)
    image_tag(url)
  end

  def flight_expired(ddate)
    ddate > Date.today
  end
end

app/views/flights/_search_result.html.erb
<% if @result[:count].eql? 0 %>
  <h4><i class="icon-close"></i> Sorry, No flights match your query.</h4>
<% else %>
  <h4><%= pluralize(@result[:count], 'result') %></h4>
<% end %>

<ul class="res">
  <% @result[:results].each do |flight| %>
    <li>
      <div class="single-flight">
        <%= form_tag(new_booking_path, method: :get) do%>
          <%= hidden_field_tag(:flight_id, flight.id) %>
          <span class="airline">
            <%= ze_logo = logo %>
            <%= hidden_field_tag(:airline_logo, parse_html(ze_logo, "//img").attr('src')) %>
            <%= flight.airline %>
            <%= hidden_field_tag(:airline, flight.airline) %>
            <small><%= flight.flight_number %></small>
            <%= hidden_field_tag(:flight_number, flight.flight_number) %>
          </span>
          <span class="dtimes">
            <time><%= flight.departure_time %></time>
            <%= hidden_field_tag(:dtime, flight.departure_time) %>
            <%= hidden_field_tag(:ddate, flight.ddate) %>
            <%= flight.departure_location.name %>
            <%= hidden_field_tag(:dname, flight.departure_location.name) %>
            <small><%= flight.departure_location.location %></small>
            <%= hidden_field_tag(:dlocation, flight.departure_location.location) %>
          </span>
          <span class="to"><i class="icon-arrow-right"></i></span>
          <span class="atimes">
            <time>
              <%= flight.arrival_time %>
              <%= hidden_field_tag(:atime, flight.arrival_time) %>
              <small>- <%= flight.adate %></small>
              <%= hidden_field_tag(:adate, flight.adate) %>
            </time>
            <%= flight.arrival_location.name %>
            <%= hidden_field_tag(:aname, flight.arrival_location.name) %>
            <small><%= flight.arrival_location.location %></small>
            <%= hidden_field_tag(:alocation, flight.arrival_location.location) %>
          </span>
          <span class="price">
            <%= flight.flight_price %>
            <%= hidden_field_tag(:price, flight.flight_price) %>
            <%= hidden_field_tag(:passengers, @result[:passengers]) %>
          </span>
          <button class="booking">Book Now</button>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>