config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  root "flights#index"

  get "booking" => "bookings#manage", as: :manage_booking

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup" => "users#new"

  get "airports" => "airports#index"

  get "search_flight" => "flights#search_flights"

  post "users/check_email" => "users#check_email", as: :check_email
  post "users/check_username" => "users#check_username", as: :check_username
  post "sessions/check_username_email" => "sessions#check_username_email",
    as: :check_username_email

  resources :users, path: "/profile"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :flight
  has_many :passengers

  extend FriendlyId
  friendly_id :booking_code, use: [:slugged, :finders]

  accepts_nested_attributes_for :passengers,
                                reject_if: :all_blank,
                                allow_destroy: true

  before_save do
    self.booking_code ||= Faker::Code.flight
  end

  validates :flight_id,
            presence: true

  private

  def should_generate_new_friendly_id?
    slug.blank? || booking_code_changed?
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :logged_in_user, only: [:index]
  before_action :set_booking_flight, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.all.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @booking = services.new_booking(
      create_booking_params,
      current_user
    )
    params[:passengers].to_i.times { @booking.passengers.build }
    render :new, locals: { f: services.parse_params(params) }
  end

  def create
    @booking = services.new_booking(booking_params, current_user)
    if @booking.save
      successful_booking(@booking, "created")
    else
      render :new, locals: {
        f: services.parse_params(
          services.parse_query_string(params[:parameters])
        )
      }
    end
  end

  def manage
    @booking = Booking.find_by(booking_code: params[:booking_code].upcase)
    @booking ? (render json: @booking.as_json) : (render json: false)
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      successful_booking(@booking, "updated")
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    flash[:success] = "Booking successfully destroyed."
    redirect_to bookings_url
  end

  private

  def set_booking_flight
    @booking = Booking.find(params[:id])
    @flight = FlightPresenter.new(Flight.find(@booking.flight_id))
  end

  def create_booking_params
    params.permit(:flight_id)
  end

  def booking_params
    params.require(:booking).permit(
      :flight_id,
      :user_id,
      :price,
      passengers_attributes: [
        :id,
        :first_name,
        :last_name,
        :email,
        :_destroy
      ]
    )
  end

  def services(booking = nil)
    BookingsServices.new(booking)
  end

  def successful_booking(booking, msg)
    services(booking).booking_email(current_user)
    flash[:success] = "Booking successfully #{msg}."
    redirect_to booking
  end
end

app/views/bookings/_form.html.erb
<section class="booking-form">
    <%= form_for @booking do |f| %>
        <%= f.hidden_field :flight_id %>
        <div class="passenger-nested-forms">
          <% if @booking.errors.any? %>
            <ul class="errors">
              <% @booking.errors.full_messages.each do |msg| %>
                <li><i class="icon-close"></i> <%= msg %></li>
              <% end %>
            </ul>
          <% end %>
          <%= f.fields_for :passengers do |p| %>
            <%= render "passenger_fields", f: p %>
          <% end %>
          <%= link_to_add_association f, :passengers do %>
            <i class="icon-user"></i> Add Passenger
          <% end %>
        </div>
        <div class="fare-details">
          <h4><i class="icon-wallet"></i> Fare details</h4>
          Passengers:&nbsp;&nbsp;&nbsp;<span><small>X</small> <span class="pass_number"><%= passengers %></span></span>
          <div class="fare"><%= price %></div>
          <%= f.hidden_field :price, id: "fare-price" %>
          <span id="ze_price" style="display: none" data-price="<%= price %>"></span>
        </div>
        <%= hidden_field_tag :parameters, request.query_string  %>
        <%= f.submit %>
    <% end %>
</section>

app/views/bookings/_manage.html.erb
<div class="modal">
  <input class="modal-state" id="manage-check" type="checkbox" />
  <div class="modal-fade-screen">
    <div class="modal-inner">
      <div class="modal-close" for="manage-check"></div>
      <h1>Manage bookings</h1>
      <p class="modal-intro">You can easily search for and edit your booking. Enter your booking number below.</p>
      <p class="modal-content">
        <%= form_tag("/booking", method: "get", remote: true, class: "form", id: "manage-bookings-form") do %>
          <p id="manage-bookings-input">
          <span class="manage-error"></span>
            <%= text_field_tag "booking_code", "", placeholder: "Enter your booking number", required: true %>
          </p>
          <p id="search-bookings-btn">
            <%= button_tag(type: "submit") do %>
              <i class="icon-plane"></i> Search Booking
            <% end %>
          </p>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/bookings/_passenger_fields.html.erb
<div class="nested-fields">
  <%= f.text_field :first_name, placeholder: "Firstname", required: true %>
  <%= f.text_field :last_name, placeholder: "Lastname", required: true %>
  <%= f.email_field :email, placeholder: "Email", required: true %>

  <%= link_to_remove_association f do %>
    <i class="icon-close"></i> Remove Passenger
  <% end %>
</div>

app/views/bookings/edit.html.erb
<% provide(:title, "Edit Booking") %>
<article>
  <section class="main-content">
    <h1>Edit your booking</h1>

    <section class="booking-pg">
      <nav class="navigation">
          <%= link_to booking_url @booking do %>
            <i class="icon-eye"></i> Show
          <% end %>
          <%= link_to edit_booking_url(@booking), class: "active" do %>
            <i class="icon-pencil"></i> Edit
          <% end %>
          <% if current_user %>
            <%= link_to @booking, method: :delete do %>
              <i class="icon-trash"></i> Delete
            <% end %>
          <% end %>
      </nav>
      <div class="manage-booking">
        <section>
          <nav>Flight</nav>
          <section class="booking-filters">
            <%= form_for @booking, html: { class: "form", id: "edit-booking" } do |f| %>
              <%= f.hidden_field :flight_id, id: "flight-id" %>
              <input type="hidden" name="booking[location]" id="location" value="<%= @flight.departure_location_id %>">
              <input type="hidden" name="booking[destination]" id="destination" value="<%= @flight.arrival_location_id %>">
              <div class="airline">
                <%= logo %>
                <br>
                <span><%= @flight.airline %></span>
                <small><%= @flight.flight_number %></small>
              </div>
              <div class="booking-flights-form">
                <span class="booking-error"></span>
                <span class="booking-info"></span>
                <h2>Flight Information</h2>
                <p class="location_airport">
                  <i class="icon-plane"></i>
                  <%= text_field_tag "", @flight.departure_location.name, id: "booking_location_name", class: "typeahead", placeholder: "Select origin" %>
                </p>
                <p class="destination_airport">
                  <i class="icon-plane"></i>
                  <%= text_field_tag "", @flight.arrival_location.name, id: "booking_destination_name", class: "typeahead", placeholder: "Select destination" %>
                </p>
                <p id="dept-date">
                  <i class="icon-calendar"></i>
                  <%= text_field_tag "when", @flight.departure_date.strftime("%d/%m/%Y"), placeholder: "Departure date", id: "ddate", class:"booking_ddate" %>
                </p>
                <h2>Passenger Information</h2>
                <div id="passengers">
                    <% if @booking.errors.any? %>
                        <ul class="errors">
                            <% @booking.errors.full_messages.each do |msg| %>
                                <li><i class="icon-close"></i> <%= msg %></li>
                            <% end %>
                        </ul>
                    <% end %>
                  <%= f.fields_for :passengers do |p| %>
                    <%= render "passenger_fields", f: p %>
                  <% end %>
                  <%= link_to_add_association f, :passengers do %>
                    <i class="icon-user"></i> Add Passenger
                  <% end %>
                </div>
              </div>
              <%= f.hidden_field :price, id: "fare-price" %>
              <span id="ze_booking_price" style="display: none" data-price="<%= number_to_currency(@flight.price, unit: '$') %>"></span>
              <%= f.submit %>
            <% end %>
          </section>
        </section>
        <aside>
          <nav>Booking</nav>
          <div class="booking_code">
            <br>
            <br>
            <span>Booking Number:</span> <%= @booking.booking_code %>
        </div>
        <br>
        <br>
        <div id="booking-price">
          <%= number_to_currency(@flight.price, unit: '$') %>
        </div>
      </aside>
    </div>
  </section>
</section>
</article>

app/views/bookings/index.html.erb
<% provide(:title, "View Bookings") %>

<section>
  <div class="main-content">
    <h1>View your bookings</h1>

    <div class="past-bookings">
      <% @bookings.each do |booking| %>
          <% flight = Flight.find(booking.flight_id) %>
          <% user = User.find(booking.user_id) %>
          <% dept = flight.departure_location %>
          <% arr = flight.arrival_location %>

          <div class="booking">
              <div class="logo">
                  <%= logo %>
              </div>
              <div class="details">
                  <span><%= flight.airline %></span> <span><%= dept.name %></span> <i class="icon-plane"></i> <span><%= arr.name %></span>
              </div>
              <div class="view">
                  <%= link_to "View", booking %>
                  <% if flight_expired(flight.departure_date) %>
                    <%= link_to booking, method: :delete, class: "cancel" do %>
                      <i class="icon-trash"></i> Cancel
                    <% end %>
                  <% end %>
              </div>
          </div>
      <% end %>
    </div>
  </div>
</section>

app/views/bookings/new.html.erb
<% provide(:title, "Bookings") %>
<article>
  <section class="main-content">
    <h1>Book your flight</h1>

    <section class="booking-pg">
        <nav><i class="icon-plane"></i> &nbsp;&nbsp;<%= f["dlocation"] %> <i class="icon-arrow-right rpt"></i> <%= f["alocation"] %></nav>
        <div class="review-booking">
            <section>
                <nav>Review your booking</nav>
                <div class="airline">
                    <%= logo(f["airline_logo"]) %>
                    <span><%= f["airline"] %></span>
                    <span><%= f["flight_number"] %></span>
                </div>
                <div class="loc_details">
                    <span><%= f["dname"] %></span>
                    <span><%= f["dtime"] %> | <%= f["ddate"] %></span>
                    <span><%= f["dlocation"] %></span>
                </div>
                <div class="sep">
                    <i class="icon-plane"></i>
                </div>
                <div class="arr_details">
                    <span><%= f["aname"] %></span>
                    <span><%= f["atime"] %> | <%= f["adate"] %></span>
                    <span><%= f["alocation"] %></span>
                </div>
            </section>
            <aside>
                <nav>Passenger details</nav>
                <%= render "form",  flight_id: f["flight_id"], price: f["price"], passengers: f["passengers"] %>
            </aside>
        </div>
    </section>
  </section>
</article>

app/views/bookings/show.html.erb
<% provide(:title, "Your Booking") %>
<article>
    <section class="main-content">
        <h1>Booking Details</h1>

        <section class="booking-pg">
            <nav class="navigation">
                <%= link_to booking_url(@booking), class: "active" do %>
                    <i class="icon-eye"></i> Show
                <% end %>
                <%= link_to edit_booking_url @booking do %>
                    <i class="icon-pencil"></i> Edit
                <% end %>
            </nav>
            <div class="review-booking">
                <section>
                    <nav>Booking</nav>
                    <div class="airline">
                        <%= logo %>
                        <span><%= @flight.airline %></span>
                        <span><%= @flight.flight_number %></span>
                    </div>
                    <div class="loc_details">
                        <span><%= @flight.departure_location.name %></span>
                        <span><%= @flight.departure_time %> | <%= @flight.ddate %></span>
                        <span><%= @flight.departure_location.location %></span>
                    </div>
                    <div class="sep">
                        <i class="icon-plane"></i>
                    </div>
                    <div class="arr_details">
                        <span><%= @flight.arrival_location.name %></span>
                        <span><%= @flight.arrival_time %> | <%= @flight.adate %></span>
                        <span><%= @flight.arrival_location.location %></span>
                    </div>
                    <div class="passenger-details">
                        <h4>Passenger Details</h4>
                        <% @booking.passengers.each do |p| %>
                            <div class="person-icon">
                                <i class="icon-people"></i>
                            </div>
                            <div class="person">
                                <span><strong>Name:</strong> <%= p.first_name %> <%= p.last_name %></span>
                                <span><strong>Email:</strong> <%= p.email %></span>
                            </div>
                        <% end %>
                    </div>
                </section>
                <aside>
                    <nav>Payment</nav>
                    <span class="booking-number"><strong>Booking Number:</strong> <%= @booking.booking_code %></span>
                    <span class="final-fare"><%= number_to_currency(@booking.price, unit: '$') %></span>
                </aside>
            </div>
        </section>
    </section>
</article>