config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  root "flights#index"

  get "booking" => "bookings#manage", as: :manage_booking

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup" => "users#new"

  get "airports" => "airports#index"

  get "search_flight" => "flights#search_flights"

  post "users/check_email" => "users#check_email", as: :check_email
  post "users/check_username" => "users#check_username", as: :check_username
  post "sessions/check_username_email" => "sessions#check_username_email",
    as: :check_username_email

  resources :users, path: "/profile"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="tia">#TIA - <%= Date.today.year %></p>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
    <nav>
        <div class="logo">
            <%= link_to image_tag("bawa.svg"), root_path %>
        </div>
    </nav>
</header>

app/views/layouts/_nav.html.erb
<div class="account" id="account">
    <ul class="ze-menu">
        <nav>Menu</nav>
        <% if logged_in? %>
            <li>
                <%= link_to bookings_path do %>
                    <i class="icon-list"></i> Past bookings
                <% end %>
            </li>
            <li>
                <%= link_to logout_path, method: "delete" do %>
                    <i class="icon-logout"></i> Logout
                <% end %>
            </li>
        <% else %>
            <li>
                <%= link_to login_path, class: "login-btn" do %>
                    <i class="icon-login"></i> Login
                <% end %>
            </li>
            <li>
                <%= link_to new_user_url do %>
                    <i class="icon-user"></i> Sign up
                <% end %>
            </li>
        <% end %>
        <li>
            <label for="manage-check">
                <i class="icon-settings"></i> <span class="modal-trigger">Manage Bookings</span>
            </label>
        </li>
    </ul>
</div>
<input type="checkbox" id="nav-trigger" class="nav-trigger" />
<label for="nav-trigger"><i class="icon-menu"></i></label>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title><%= full_title(yield(:title)) %></title>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,800,700,600,300' rel='stylesheet' type='text/css'>
        <link href='//fonts.googleapis.com/css?family=Roboto+Slab:400,300,100,700' rel='stylesheet' type='text/css'>
        <%= javascript_include_tag 'application', 'jquery.validate.min', 'additional-methods.min', 'type-ahead.min', 'jquery.datetimepicker.full.min', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <%= render "layouts/nav" %>
        <div class="wrap">
            <%= render "layouts/header" %>
            <main class="content" id="panel">
                <% flash.each do |message_type, message| %>
                    <%= content_tag(:div, message, class: "flash-#{message_type}") %>
                <% end %>
                <%= yield %>
            </main>
            <%= render partial: "bookings/manage" %>
            <%= render "layouts/footer" %>
        </div>
    </body>
</html>